export class UserProfile {
	id? : string;
	FirstName? : string;
	LastName? : string;
	Sex? : string;
	Email? : string;
	HomePhone? : string;
	CellPhone? : string;
	Address1? : string;
	Address2? : string;
	City? : string;
	State? : string;
	ZipCode? : string;
	Country? : string;
	CurrentCompanySchool? : string;
	CurrentPosition?: string;
	FaceBookURL? : string;
	LinkedinURL? : string;
	PersonalWebsite? : string;
	EmploymentType? : string;
	DesiredPosition? : string;
	DesiredSalary? : string;
	IsRelocate? : boolean;
	IsTravel? : boolean;
	YearsofExperince? : string;
	WorkAuthorization? : string;
	SecurityClearance? : boolean;
    // ResumeID? : string;
    // ResumeFileName? : string;
	// ResumeURL? : string;
	// ResumeExt? :string;
	CoverLetter? : string;
	institute? : string;
	instituteCity? : string;
	instituteCountry? : string;
	SkillSet? : string;
	Education? : string;
	SalaryExpectation? : string;
	UserID? : string;
	Username? : string;
	isSearchable? : boolean;
	CreatedDate? : Date;
	LastModifiedDate? : Date;
	objectID? : string;
}

